export type Dining = {
  id: string;
  slug: string;
  title: string;
  category: string;
  desc: string;
  heroSubtitle: string;
  rating: number;
  reviewCount: string;
  legacyTitlePrefix: string;
  legacyTitleHighlight: string;
  legacyDescription1: string;
  legacyDescription2: string;
  heroImageId: string;
  legacy1Id: string;
  legacy2Id: string;
  visualImageIds: string[];
  mapImgId: string;
  locationAddress: string;
  locationCoordinates: string;
};

export const diningList: Dining[] = [
  {
    id: 'res-cinnamon',
    slug: 'cinnamon-bey',
    title: 'Cinnamon Bey',
    category: 'Boutique',
    desc: 'Enjoy a delightful dining experience with expertly prepared dishes, welcoming service, and a comfortable atmosphere perfect for family meals, gatherings, and special occasions.',
    heroSubtitle: 'Discover the best restaurants, cafes, dining experience.',
    rating: 4.8,
    reviewCount: '1k+',
    legacyTitlePrefix: 'A Legacy of ',
    legacyTitleHighlight: 'Culinary Innovation',
    legacyDescription1: "Founded by Chef Julian Vance in the heart of Marbella, Lumière d'Or began as a humble family bistro. Over three decades, it has evolved into a sanctuary for those who seek the extraordinary. Our concept revolves around 'Elemental Gastronomy'—respecting the raw integrity of ingredients while using modern precision to unlock hidden flavors.",
    legacyDescription2: 'Every dish tells a story of the soil, the sea, and the season. We believe that luxury is not just about the ingredients, but the soul that prepares them.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: 'Cinnamon Bey Beruwala, Beruwala 12070',
    locationCoordinates: '6.4764° N, 79.9818° E',
  },
  {
    id: 'res-villey',
    slug: 'villey-restaurant',
    title: 'Villey Restaurant',
    category: 'Luxury',
    desc: 'Relax in a stylish, breezy setting reflecting sea surges and warm sand motifs, creating a serene environment while adding vibrancy for a casual and fun vibe.',
    heroSubtitle: 'A breezy culinary escape by the sea.',
    rating: 4.7,
    reviewCount: '800+',
    legacyTitlePrefix: 'The Art of ',
    legacyTitleHighlight: 'Coastal Dining',
    legacyDescription1: "Villey Restaurant brings the ocean to your plate with an ever-changing menu inspired by the daily catch. Our open-air design ensures that every meal is accompanied by a fresh sea breeze.",
    legacyDescription2: 'We source all our ingredients locally, supporting the nearby fishing communities and organic farmers to bring you the freshest flavors.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: '12 Beach Road, Mirissa',
    locationCoordinates: '5.9483° N, 80.4571° E',
  },
  {
    id: 'res-hilton',
    slug: 'hilton-hotel',
    title: 'Hilton Hotel',
    category: 'Luxury',
    desc: 'Discover authentic local flavors and traditional recipes that showcase the unique culinary heritage and culture of the destination.',
    heroSubtitle: 'Five-star dining in the heart of the city.',
    rating: 4.9,
    reviewCount: '2k+',
    legacyTitlePrefix: 'Excellence in ',
    legacyTitleHighlight: 'Global Cuisine',
    legacyDescription1: "The Hilton dining experience is synonymous with world-class quality. From authentic Sri Lankan buffets to fine dining international cuisines, our master chefs curate a diverse array of culinary delights.",
    legacyDescription2: 'Our heritage lies in blending global standards with local warmth, creating an unforgettable dining journey for every guest.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: 'Sir Macan Markar Mawatha, Colombo',
    locationCoordinates: '6.9271° N, 79.8612° E',
  },
  {
    id: 'res-amber',
    slug: 'amber-room',
    title: 'Amber Room',
    category: 'Boutique',
    desc: 'An intimate dining experience focusing on the spice routes of old Ceylon.',
    heroSubtitle: 'Taste the history of the spice island.',
    rating: 4.6,
    reviewCount: '450+',
    legacyTitlePrefix: 'Journey Through ',
    legacyTitleHighlight: 'Spice Routes',
    legacyDescription1: "The Amber Room is a tribute to Ceylon's rich history as the center of the global spice trade. Our dishes incorporate ancient spice blends passed down through generations.",
    legacyDescription2: 'Dine in an intimate setting adorned with colonial era artifacts and amber lighting that sets a warm, nostalgic mood.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: 'Galle Fort, Galle',
    locationCoordinates: '6.0328° N, 80.2170° E',
  },
  {
    id: 'res-azure',
    slug: 'azure-terrace',
    title: 'Azure Terrace',
    category: 'Cafe',
    desc: 'Fresh sea breezes and lighter fare make this the perfect afternoon retreat.',
    heroSubtitle: 'Relax with ocean views and light bites.',
    rating: 4.5,
    reviewCount: '600+',
    legacyTitlePrefix: 'Casual ',
    legacyTitleHighlight: 'Afternoon Elegance',
    legacyDescription1: "Azure Terrace offers a laid-back atmosphere perfect for a light lunch or sunset cocktails. Overlooking the azure waters, it's a favorite spot for both locals and travelers.",
    legacyDescription2: 'Enjoy our signature tapas and artisanal coffee while taking in the panoramic views of the coastline.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: 'Marine Drive, Colombo',
    locationCoordinates: '6.8920° N, 79.8549° E',
  },
  {
    id: 'res-spice',
    slug: 'spice-cellar',
    title: 'The Spice Cellar',
    category: 'Traditional',
    desc: 'Dive deep into the roots of Sri Lankan curry and rice in a heritage setting.',
    heroSubtitle: 'Authentic local flavors crafted with passion.',
    rating: 4.8,
    reviewCount: '1.2k+',
    legacyTitlePrefix: 'Authentic ',
    legacyTitleHighlight: 'Heritage Recipes',
    legacyDescription1: "The Spice Cellar is dedicated to preserving the authentic recipes of Sri Lankan grandmothers. Our curries are slow-cooked in clay pots over wood fires to achieve that unmistakable smoky flavor.",
    legacyDescription2: 'Experience the true warmth of Sri Lankan hospitality in a rustic, cellar-like ambiance that transports you to a bygone era.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: 'Lake Road, Kandy',
    locationCoordinates: '7.2906° N, 80.6337° E',
  },
  {
    id: 'res-golden',
    slug: 'golden-sands',
    title: 'Golden Sands',
    category: 'Boutique',
    desc: 'Beachfront luxury dining with a focus on sustainable seafood.',
    heroSubtitle: 'Dine on the sands under the stars.',
    rating: 4.7,
    reviewCount: '950+',
    legacyTitlePrefix: 'Sustainable ',
    legacyTitleHighlight: 'Seafood Mastery',
    legacyDescription1: "Golden Sands redefines beachfront dining with its commitment to sustainable and ethically sourced seafood. Enjoy your meal with your toes in the sand and the sound of waves in the background.",
    legacyDescription2: 'Our chefs work closely with local fishermen to ensure only the highest quality and responsibly caught seafood reaches your plate.',
    heroImageId: 'res-cinnamon',
    legacy1Id: 'res-legacy-1',
    legacy2Id: 'res-legacy-2',
    visualImageIds: ['visual-1', 'visual-2', 'visual-3', 'visual-4'],
    mapImgId: 'res-map',
    locationAddress: 'Beach Road, Negombo',
    locationCoordinates: '7.2008° N, 79.8398° E',
  }
];
